version: '3.8'

services:
  arxiv_agent:
    build:
      context: .
      dockerfile: linguistic_analysis_docker_file  # This assumes your Dockerfile is named exactly "Dockerfile"
    ports:
      - "8011:8011"
    stdin_open: true
    tty: true
    networks:
      - uagents-net

networks:
  uagents-net:
